language: python cpp

compiler: - gcc

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
    - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
install:
    # installing  requirements for kattis problem tools
    # note that on debian/ubuntu pip tools are being installed to the python2 pip
    # install kattis problem tools
    - chmod +x install.sh
    - sudo ./install.sh
    - sudo pip2 install git+https://github.com/kattis/problemtools

script:
    - verifyproblem armorhere
    - verifyproblem craftmines
    - verifyproblem dangtiles
    - verifyproblem melzarmaze
    - verifyproblem silentmist
    - verifyproblem slaykayran
    - verifyproblem standbehindbraum
    - verifyproblem thewayforward
