language: python

install:
    # installing  requirements for kattis problem tools
    # note that on debian/ubuntu pip tools are being installed to the python2 pip
    # install kattis problem tools
    - chmod +x install.sh
    - sudo ./install.sh
    - sudo pip2 install git+https://github.com/kattis/problemtools

script:
    - verifyproblem armorhere
    - verifyproblem craftmines
    - verifyproblem dangtiles
    - verifyproblem melzarmaze
    - verifyproblem silentmist
    - verifyproblem slaykayran
    - verifyproblem standbehindbraum
    - verifyproblem thewayforward
