language: python

compiler: g++

before_install:
    - sudo apt-get install buildessentials
install:
    # installing  requirements for kattis problem tools
    # note that on debian/ubuntu pip tools are being installed to the python2 pip
    # install kattis problem tools
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - chmod +x install.sh
    - sudo ./install.sh
    - sudo pip2 install git+https://github.com/kattis/problemtools

script:
    - verifyproblem armorhere
    - verifyproblem craftmines
    - verifyproblem dangtiles
    - verifyproblem melzarmaze
    - verifyproblem silentmist
    - verifyproblem slaykayran
    - verifyproblem standbehindbraum
    - verifyproblem thewayforward
