language: python

install:
    # installing  requirements for kattis problem tools
    # note that on debian/ubuntu pip tools are being installed to the python2 pip
    # install kattis problem tools
    - chmod +x install.sh
    - sudo ./install.sh
    - git clone https://github.com/Kattis/problemtools.git
    - cd problemtools
    - pip install -r requirements.txt
    - cd ..

script:
    - verifyproblem armorhere
    - verifyproblem craftmines
    - verifyproblem dangtiles
    - verifyproblem melzarmaze
    - verifyproblem silentmist
    - verifyproblem slaykayran
    - verifyproblem standbehindbraum
    - verifyproblem thewayforward